name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest GHH version
      uses: ./latest-gloomhaven-helper-action
      id: version

    - name: Build and push Docker images
      uses: docker/build-push-action@v1
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        repository: grepnull/gloomhaven-helper-headless
        build_args: "version=${{ steps.version.outputs.version }}"
        tag_with_ref: true
        tag_with_sha: true
        tags: "${{ steps.version.outputs.version }},${{ steps.version.outputs.major }},${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
        add_git_labels: true

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: grepnull
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: grepnull/gloomhaven-helper-headless
