name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get latest GHH version
      uses: ./latest-gloomhaven-helper-action
      id: version

    - name: Build and push Docker images
      uses: aevea/action-kaniko@v0.5.0
      with:
        username: grepnull
        password: ${{ secrets.DOCKER_KEY }}
        image: grepnull/gloomhaven-helper-headless
        cache: true
        cache_registry: grepnull/cache
        skip_unchanged_digest: true
        extra_args: "--build-arg version=${{ steps.version.outputs.version }}"
#"${{ steps.version.outputs.version }},${{ steps.version.outputs.major }},${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }
      # uses: docker/build-push-action@v1
      # env:
      #   DOCKER_BUILDKIT: 1
      # with:
      #   username: grepnull
      #   password: ${{ secrets.DOCKER_KEY }}
      #   repository: grepnull/gloomhaven-helper-headless
      #   always_pull: true
      #   cache_froms: grepnull/gloomhaven-helper-headless:auto-ci,openjdk:14.0.2-slim-buster
      #   build_args: "version=${{ steps.version.outputs.version }},BUILDKIT_INLINE_CACHE=1"
      #   tag_with_ref: true
      #   tag_with_sha: true
      #   tags: "${{ steps.version.outputs.version }},${{ steps.version.outputs.major }},${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}"
      #   add_git_labels: true

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      env:
        DOCKERHUB_USERNAME: grepnull
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: grepnull/gloomhaven-helper-headless
